menu:
  Home: /
  Archives: /archives

widgets:
- search

cover:
  enable: true
  url: http://ww1.sinaimg.cn/large/6cea169fjw1edgyzma1xcj21kw16ohba.jpg
   
excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook:
  twitter:
  google: true
  pinterest:

fancybox: true

google_analytics: UA-36877105-1
rss:

comment_provider: duoshuo

# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light

# Duoshuo comment
duoshuo:
  short_name: daisygao

social:
  github: https://github.com/daisygao
  weibo: http://weibo.com/mousang
  google_plus: 

social:
  github: https://github.com/your_name
  weibo: http://weibo.com/your_name

auto_change:
  enable: true
