<<<<<<< HEAD
categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
prev: Prev
next: Next
newer: Next
older: Prev
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: "Page %d"
recent_posts: Recent Posts
=======
categories: 'Categories'
search: 'Search'
tags: 'Tags'
tagcloud: 'Tag Cloud'
tweets: 'Tweets'
prev: 'Prev'
next: 'Next'
newer: 'Next'
older: 'Prev'
comment: 'Comments'
archive_a: 'Archives'
archive_b: 'Archives: %s'
page: 'Page %d'
recent_posts: 'Recent Posts'
>>>>>>> 3d1392fb3efd0cd37451ea701b3597f3cd8ab258
